# https://docs.github.com/en/actions/learn-github-actions/contexts

name: version-tag

permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths-ignore: []

jobs:
  version-tag:
    runs-on: ubuntu-latest
    steps:

      - name: version
        run: |
          VERSION=$( date '+%y.%m%d.%H%M' | sed 's/\.0*/./g' )
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: tag
        run: |
          git config user.name github-actions
          git config user.email "github-actions@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION


